### ISSUE TITLE
[FCC Beta] Required Improvements in Search functionality & its UX

### ISSUE THREAD

**Issue by vkWeb** [freeCodeCamp/react-freecodecamp-search#55]
@Bouncey I was playing with the search bar and found some glitches which need to be addressed. All issues related to search bar from freeCodeCamp repo are merged in this issue and it is frequently updated.

#### Functionality Issues
- [ ] Right-clicking on output search modal or on opening chrome dev tools the modal disappears. It should disappear only when clicked outside the modal.   
- [ ] Searching a term multiple times consecutively doesn't show the results. 
- [ ] If the searched term doesn't match any category, an appropriate message must be displayed.-[ 
- [ ] No search results are shown when characters are less than 3. (FCC issue [#16791](https://github.com/freeCodeCamp/freeCodeCamp/issues/16791))

#### User Interface/UI/UX Issues
- [ ] The output search modal is overflowing i.e. it needs a scrollbar. 
- [ ] The highlighting style of searched text needs to be changed. <details><summary>Screenshot and details.</summary>The highlighting style is causing an accessibility issue here. 
![2018-02-20](https://user-images.githubusercontent.com/26724128/36395326-a5145900-15de-11e8-90ab-cbf106edbc31.png)</details>
- [ ] In night mode search results text are Illegible. (FCC issue [#16787](https://github.com/freeCodeCamp/freeCodeCamp/issues/16787))

**Comment by leonfeng** [comment]
• I've tried various search terms but nothing is ever found under the Challenge category. For instance, searching for "cert" matches "cet", "cer", and "cart" (feature?), but not the challenge titled "Claim Your JavaScript Algorithms and Data Structures Certificate".
![screen shot 2018-03-14 at 18 25 24](https://user-images.githubusercontent.com/241553/37412090-b5ca093e-27bd-11e8-91e8-144369fb8dc4.png)

• Switching to another browser tab and then back dismisses the search results modal and clears the search input.

**Comment by Bouncey** [comment]
All development relating to this component is now being carried out in the [freecodecamp/search-mono-repo](https://github.com/freeCodeCamp/search-mono-repo). This repository will now be archived.

I will reopen this issue there.
