### ISSUE TITLE
Beta: Search bar showing no results / not working 

### ISSUE THREAD

**Issue by moT01** [freeCodeCamp/react-freecodecamp-search#56]
I opened an issue on the main repo - I was told to put it here I believe...

The issue seems to work like this:
I can search successfully as many times as I want until I switch pages.

For example: If I first search on the settings page, I can make searches just fine - then I close the search results - then I go to the map page and searching doesn't work.

Another example: if reload the base url - the map is open - I search there and it works - then close the search results - then I go to the settings page can't make searches.

It doesn't happen if I leave the search results open.
Here's a link to my original issue with some more details - and some other issues
https://github.com/freeCodeCamp/freeCodeCamp/issues/16791

**Comment by moT01** [comment]
On a side note - search results don't show unless I use at least 3 characters - but I will assume that's intentional

**Comment by vkWeb** [comment]
@moT01 Please close this. I've covered your issues on #55.

**Comment by moT01** [comment]
@vkWeb You sure it wouldn't be better to split your issue into multiple issues? - since they aren't all related. Seems like there's a number of issues there that might be tough to tackle at one time.

**Comment by vkWeb** [comment]
@moT01 Actually, the reason why I'm doing this is that we'll be able to look up everything in one issue then we'll complete tasks in parts or phases. If the list gets too long, I'll break it into multiple issues. Looks good, right?
